### ISSUE TITLE
UnicodeDecodeError in xlib.py 

### ISSUE THREAD

**Issue by nikanar** [ActivityWatch/aw-watcher-window#21]
Some internet page title caught the aw-window-watcher by surprise :

```
2017-07-20 16:20:19,793 [INFO ]: No longer AFK  (aw_watcher_afk.afk:99)
2017-07-20 16:30:45,707 [INFO ]: Became AFK  (aw_watcher_afk.afk:105)
2017-07-20 16:31:05,738 [INFO ]: No longer AFK  (aw_watcher_afk.afk:99)
2017-07-20 17:51:01,673 [ERROR]: Exception thrown while trying to get active window: 'bytes' object has no attribute 'encode'  (aw_watcher_window.main:73)
Traceback (most recent call last):
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/xlib.py", line 62, in get_window_name
    return d.value.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 40: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/main.py", line 70, in heartbeat_loop
    current_window = get_current_window()
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 44, in get_current_window
    return get_current_window_linux()
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 14, in get_current_window_linux
    name = xlib.get_window_name(window)
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/xlib.py", line 64, in get_window_name
    return d.value.encode('utf8').decode('utf8')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aw-watcher-window", line 11, in <module>
    load_entry_point('aw-watcher-window==0.2', 'console_scripts', 'aw-watcher-window')()
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/main.py", line 45, in main
    heartbeat_loop(client, bucket_id, poll_time=args.poll_time, exclude_title=args.exclude_title)
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/main.py", line 74, in heartbeat_loop
    traceback.print_exc(e)
  File "/usr/lib/python3.6/traceback.py", line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.6/traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/usr/lib/python3.6/traceback.py", line 486, in __init__
    _seen=_seen)
  File "/usr/lib/python3.6/traceback.py", line 497, in __init__
    capture_locals=capture_locals)
  File "/usr/lib/python3.6/traceback.py", line 332, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'AttributeError' and 'int'
Reading active process stderr...
Traceback (most recent call last):
  File "/home/will/.local/lib/python3.6/site-packages/aw_qt-0.1-py3.6.egg/aw_qt/trayicon.py", line 110, in rebuild_modules_menu
    show_module_failed_dialog(module)
  File "/home/will/.local/lib/python3.6/site-packages/aw_qt-0.1-py3.6.egg/aw_qt/trayicon.py", line 96, in show_module_failed_dialog
    box.setDetailedText(module.stderr())
  File "/home/will/.local/lib/python3.6/site-packages/aw_qt-0.1-py3.6.egg/aw_qt/manager.py", line 108, in stderr
    self._log += self._process.stderr.read()
AttributeError: 'NoneType' object has no attribute 'read'
Aborted (core dumped)
```

Not sure how I got it, couldn't reproduce by browsing around the same pages with possible strange characters in window title, and then some.

maybe line 63 of `xlib.py`, which currently reads `except UnicodeError:`, should be `except UnicodeError, UnicodeDecodeError:`, since it seems to be a catch-all-and-coerce type code block anyway. But I dunno.

**Comment by johan-bjareholt** [comment]
Changing from UnicodeError to UnicodeDecodeError will not fix it since the decode error is a [subclass of UnicodeError](https://docs.python.org/3.6/library/exceptions.html#UnicodeDecodeError).

However, when you look at the second exception you see that it points at line 64 which was the catch of the first exception. 

```
        # Fixing utf8 issue on Ubuntu (https://github.com/gurgeh/selfspy/issues/133)
        # Thanks to https://github.com/gurgeh/selfspy/issues/133#issuecomment-142943681
        try:
            return d.value.decode('utf8')
        except UnicodeError:
            return d.value.encode('utf8').decode('utf8')
```

What do do about it though? No idea

**Comment by nikanar** [comment]
https://stackoverflow.com/a/37979853 suggests it's probably the EURO character `€` in encoding `cp-1252`.

https://stackoverflow.com/a/12468274 suggests `d.value.decode('utf-8', "ignore")` - or `backslashreplace` (by `\\x80`) or `replace` (by `U+FFFD REPLACEMENT CHARACTER`), cf [docs](https://docs.python.org/3/howto/unicode.html#the-unicode-type) - to deal with the error.

**Comment by johan-bjareholt** [comment]
"ignore" simply skips the unknown characters, so it's more like avoiding the problem instead of fixing it. But since there is no standard window title encoding there's probably no way to do it properly, so maybe we should start using it on the exception part.

What do you think @ErikBjare ?

**Comment by ErikBjare** [comment]
Falling back to using "ignore" seems reasonable, although we should probably log a warning everytime it's needed.

**Comment by johan-bjareholt** [comment]
This should be enough https://github.com/ActivityWatch/aw-watcher-window/commit/911dd78dc9d6a882a2367f5a083ac4111a108f1b

I'll close for now, open again if there are any other related issues.

**Comment by nikanar** [comment]
Update :

```
bytes are : b'[...] Play arisreyes in vSpuddPu \xe2 vSpuddPu \xe2\x80\xa2 [...]'
[...]
    return d.value.encode('utf8').decode('utf8', 'ignore')
AttributeError: 'bytes' object has no attribute 'encode'
```

The stray `\xe2` is strange, as is the repeated "vSpuddPu". The normal title for that window is `[...] Play arisreyes in vSpuddPu \xe2\x80\xa2 [...]`.

`\xe2\x80\xa2` is U+2022 "•" BULLET, that part seems normal.

<details>
<summary>full log</summary>

```
2017-07-27 21:50:37,549 [WARNING]: Failed to decode one or more characters which will be skipped, bytes are: b'Your turn - Play arisreyes in vSpuddPu \xe2 vSpuddPu \xe2\x80\xa2 lichess.org - Goog'  (aw_watcher_window.xlib:66)
2017-07-27 21:50:37,550 [ERROR]: Exception thrown while trying to get active window: 'bytes' object has no attribute 'encode'  (aw_watcher_window.main:69)
Traceback (most recent call last):
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/xlib.py", line 64, in get_window_name
    return d.value.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 39: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/main.py", line 66, in heartbeat_loop
    current_window = get_current_window()
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 44, in get_current_window
    return get_current_window_linux()
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 14, in get_current_window_linux
    name = xlib.get_window_name(window)
  File "/home/will/.local/lib/python3.6/site-packages/aw_watcher_window/xlib.py", line 67, in get_window_name
    return d.value.encode('utf8').decode('utf8', 'ignore')
AttributeError: 'bytes' object has no attribute 'encode'
```
</details>

**Comment by ErikBjare** [comment]
Seems we need a check to avoid the `.encode('utf8')` if the d.value object is a bytes object.

**Comment by ErikBjare** [comment]
So @nikanar's PR above should have fixed that specific issue.

Please leave a comment or open a new issue (depending on how related it is) if there are further problems.
