### ISSUE TITLE
Error shows after running for a day constantly

### ISSUE THREAD

**Issue by yratof** [ActivityWatch/aw-watcher-window#25]
This error shows up when leaving the computer inactive overnight – might be useful to note:

    IndexError: list index out of range
    /Users/igatnas/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/printAppTitle.scpt: execution error: git: 'pull && hub checkout develop && hub pull (git)"' is not a git command. See 'git --help'. (1)
    2017-09-07 09:57:36 [ERROR]: Exception thrown while trying to get active window: list index out of range  (aw_watcher_window.main:69)
    Traceback (most recent call last):
      File "/Users/igatnas/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/main.py", line 66, in heartbeat_loop
        current_window = get_current_window()
      File "/Users/igatnas/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 46, in get_current_window
        return get_current_window_macos()
      File "/Users/igatnas/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 23, in get_current_window_macos
        title = macos.getTitle(info)
      File "/Users/igatnas/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/macos.py", line 17, in getTitle
        return info.split('","')[1][:-1]
    IndexError: list index out of range

**Comment by yratof** [comment]
There are no logs for this time, presume that the error stopped that. But the url was a wordpress admin for a site I'm working on – using Chrome Version 60.0.3112.113

**Comment by ErikBjare** [comment]
I'm kind of confused about the second line, why is git mentioned there?

Are you able to replicate?

**Comment by ErikBjare** [comment]
This error could be mitigated if #14 is solved.

**Comment by yratof** [comment]
Well, looking at the terminal again, it's happened about 50 times  in the last few hours, but then resolves:

    IndexError: list index out of range
    sh: -c: line 1: syntax error: unexpected end of file (2)n3.6/site-packages/aw_watcher_window/printAppTitle.scpt: execution error: sh: -c: line 0: unexpected EOF while looking for matching `''
    2017-09-07 13:31:11 [ERROR]: Exception thrown while trying to get active window: list index out of range  (aw_watcher_window.main:69)
    Traceback (most recent call last):
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/main.py", line 66, in heartbeat_loop
        current_window = get_current_window()
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 46, in get_current_window
        return get_current_window_macos()
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 23, in get_current_window_macos
        title = macos.getTitle(info)
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/macos.py", line 17, in getTitle
        return info.split('","')[1][:-1]
    IndexError: list index out of range
    sh: -c: line 1: syntax error: unexpected end of file (2)n3.6/site-packages/aw_watcher_window/printAppTitle.scpt: execution error: sh: -c: line 0: unexpected EOF while looking for matching `''
    2017-09-07 13:31:11 [ERROR]: Exception thrown while trying to get active window: list index out of range  (aw_watcher_window.main:69)
    Traceback (most recent call last):
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/main.py", line 66, in heartbeat_loop
        current_window = get_current_window()
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 46, in get_current_window
        return get_current_window_macos()
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 23, in get_current_window_macos
        title = macos.getTitle(info)
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/macos.py", line 17, in getTitle
        return info.split('","')[1][:-1]
    IndexError: list index out of range
    sh: -c: line 1: syntax error: unexpected end of file (2)n3.6/site-packages/aw_watcher_window/printAppTitle.scpt: execution error: sh: -c: line 0: unexpected EOF while looking for matching `''
    2017-09-07 13:31:11 [ERROR]: Exception thrown while trying to get active window: list index out of range  (aw_watcher_window.main:69)
    Traceback (most recent call last):
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/main.py", line 66, in heartbeat_loop
        current_window = get_current_window()
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 46, in get_current_window
        return get_current_window_macos()
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 23, in get_current_window_macos
        title = macos.getTitle(info)
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/macos.py", line 17, in getTitle
        return info.split('","')[1][:-1]
    IndexError: list index out of range
    sh: -c: line 1: syntax error: unexpected end of file (2)n3.6/site-packages/aw_watcher_window/printAppTitle.scpt: execution error: sh: -c: line 0: unexpected EOF while looking for matching `''
    2017-09-07 13:31:11 [ERROR]: Exception thrown while trying to get active window: list index out of range  (aw_watcher_window.main:69)
    Traceback (most recent call last):
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/main.py", line 66, in heartbeat_loop
        current_window = get_current_window()
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 46, in get_current_window
        return get_current_window_macos()
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 23, in get_current_window_macos
        title = macos.getTitle(info)
      File "/Users/fancynamehere/Projects/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_window/macos.py", line 17, in getTitle
        return info.split('","')[1][:-1]
    IndexError: list index out of range

**Comment by ErikBjare** [comment]
Alright, won't be able to fix this right now but thanks for reporting.

**Comment by vilos** [comment]
I've got similar problem with printAppTitle.scpt recently,  probably also when I left my machine run overnight:

```
2018-05-18 10:10:30 [ERROR]: Exception thrown while trying to get active window: list index out of range  (aw_watcher_window.main:69)
/Users/user/venv/activitywatch/lib/python3.5/site-packages/aw_watcher_window/printAppTitle.scpt:0:13: script error: A real number can't go after this identifier. (-2740)
Traceback (most recent call last):
  File "/Users/user/venv/activitywatch/lib/python3.5/site-packages/aw_watcher_window/main.py", line 66, in heartbeat_loop
    current_window = get_current_window()
  File "/Users/user/venv/activitywatch/lib/python3.5/site-packages/aw_watcher_window/lib.py", line 46, in get_current_window
    return get_current_window_macos()
  File "/Users/user/venv/activitywatch/lib/python3.5/site-packages/aw_watcher_window/lib.py", line 23, in get_current_window_macos
    title = macos.getTitle(info)
  File "/Users/user/venv/activitywatch/lib/python3.5/site-packages/aw_watcher_window/macos.py", line 17, in getTitle
    return info.split('","')[1][:-1]
IndexError: list index out of range
```
