### ISSUE TITLE
window watcher crashes on Chrome Task Manager window

### ISSUE THREAD

**Issue by nikanar** [ActivityWatch/aw-watcher-window#27]
Opening chrome's task manager (shortcut : Shift-Escape), a pop-up appears stating :

> Module aw-watcher-window quit unexpectedly [Restart] [Show details] [Cancel]

Details are

    2017-11-21 17:12:57 [INFO ]: Running watcher with poll time 1.0 seconds  (aw_watcher_window.main:35)
    2017-11-21 17:12:57 [INFO ]: aw-watcher-window has started  (aw_watcher_window.main:44)
    2017-11-21 17:12:57 [INFO ]: Connection to aw-server established  (aw_client.client:281)
    2017-11-21 18:10:56 [ERROR]: Exception thrown while trying to get active window: [Errno 5] Input/output error  (aw_watcher_window.main:69)

Pressing "restarting" in the notification popup only makes it crash again (with the same details), for so long as the active window is chrome's task manager. If I restart the watcher with an other window being active, it restarts fine and is stable. And crashes right again as soon as the task manager becomes active again (as my mouse goes over
it, as focus follows mouse in my awesome wm).

<details>
<summary>xprop details</summary>

```will@ker:~$ xprop 
_NET_WM_STATE(ATOM) = 
_NET_WM_DESKTOP(CARDINAL) = 7
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 2417562315
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1150, 20
		program specified minimum size: 460 by 270
WM_NAME(UTF8_STRING) = "Task Manager - Google Chrome"
_NET_WM_NAME(UTF8_STRING) = "Task Manager - Google Chrome"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_ICON(CARDINAL) = 	Icon (64 x 64):
                        <chrome icon in ascii>	                                                                
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 24459
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "ker"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

</details>

**Comment by johan-bjareholt** [comment]
Oh, that's not good at all.

I seem to not be able to reproduce though, not sure why.

I am currently on my debian machine though, can try on my arch linux machine later today (you are also

```
12.08s ago
duration10s
title: Task Manager - Google Chrome
app: unknown
```
<details>
<summary>xprop details</summary>
```
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 1
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 39, 1
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE,     NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE,  NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ,   NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP,  NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_USER_TIME(CARDINAL) = 330412
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1050, 575
		program specified minimum size: 460 by 316
WM_NAME(UTF8_STRING) = "Task Manager - Google Chrome"
_NET_WM_NAME(UTF8_STRING) = "Task Manager - Google Chrome"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_ICON(CARDINAL) = 	Icon (64 x 64): <redacted>
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 2693
WM_LOCALE_NAME(STRING) = "en_US.utf8"
WM_CLIENT_MACHINE(STRING) = "lnxjohanbj"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```
</details>

It's odd that it crashes though, when looking at the code the exception is supposed to be handled:



```
try:
    current_window = get_current_window()
    logger.debug(current_window)
except Exception as e:
    logger.error("Exception thrown while trying to get active window: {}".format(e))
    traceback.print_exc()
    current_window = {"appname": "unknown", "title": "unknown"}
```

In this case "appname" and "title" should just be sent as "unknown" and is not supposed to crash.

Can you reproduce this without aw-qt and see if there's some more information in stdout/stderr? The `traceback.print_exc()` line is not printing to log output i believe. And if something goes wrong in the error handling (which is my assumption), that traceback should also be visible.

**Comment by nikanar** [comment]
Nope ! Cannot exactly reproduce. I killed aw-qt, started aw-watcher-window, and went to that window, and it doesn't crash anymore. It does [WARN] like crazy though :

```
2017-11-22 14:32:24 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:91)
2017-11-22 14:32:24 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:91)
2017-11-22 14:32:25 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:91)
2017-11-22 14:32:25 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:91)
2017-11-22 14:32:25 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:91)
```

I get 3 of these per second so long as said window is active. It stops when I focus other windows.

Then I restarted the whole aw-qt, and it again doesn't crash, only flood warnings.

**Comment by nikanar** [comment]
So it seems this is a known problem, described [here](https://stackoverflow.com/questions/10409897/ioerror-input-output-error-when-printing) and [here](https://stackoverflow.com/q/38238139/1449460) on SO. Basically the watcher (/aw-qt) tries to print to stdout (`logger.error` or `traceback.print_exc()`) but cannot because the terminal was detached, so the print raises an Error.

I changed the above to

```
        except Exception as e:
            traceback.print_exc(file = open("/home/will/aw-qt.traceback", "a"))
            logger.error("Exception thrown while trying to get active window: {}".format(e))
            traceback.print_exc()
```

and got the traceback :

```
will@ker:~$ cat aw-qt.traceback 
Traceback (most recent call last):
  File "/home/will/15-QS/2-Activitywatch/aw-watcher-window/aw_watcher_window/main.py", line 66, in heartbeat_loop
    current_window = get_current_window()
  File "/home/will/15-QS/2-Activitywatch/aw-watcher-window/aw_watcher_window/lib.py", line 44, in get_current_window
    return get_current_window_linux()
  File "/home/will/15-QS/2-Activitywatch/aw-watcher-window/aw_watcher_window/lib.py", line 13, in get_current_window_linux
    cls = xlib.get_window_class(window)
  File "/home/will/15-QS/2-Activitywatch/aw-watcher-window/aw_watcher_window/xlib.py", line 90, in get_window_class
    print("")
OSError: [Errno 5] Input/output error
```

**Comment by ym1234** [comment]
Any reason this hasn't been fixed?

**Comment by johan-bjareholt** [comment]
@ym1234 Personally I can't fix it because I can't reproduce it. Are you experiencing the issue?
