### ISSUE TITLE
[Windows] aw watcher window does not track correctly

### ISSUE THREAD

**Issue by IamRezaMousavi** [ActivityWatch/aw-watcher-window#82]
This is my log message:

```
2022-12-11 18:40:20 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
2022-12-11 18:40:21 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:429)
2022-12-11 18:56:47 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:110)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 107, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 57, in get_current_window
  File "aw_watcher_window\lib.py", line 40, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 324, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217385, 'OLE error 0x80041017', None, None)
2022-12-11 18:56:48 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:110)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 107, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 57, in get_current_window
  File "aw_watcher_window\lib.py", line 40, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 324, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217385, 'OLE error 0x80041017', None, None)
2022-12-11 18:58:53 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:110)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 107, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 57, in get_current_window
  File "aw_watcher_window\lib.py", line 40, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 324, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217385, 'OLE error 0x80041017', None, None)
2022-12-11 18:58:54 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:110)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 107, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 57, in get_current_window
  File "aw_watcher_window\lib.py", line 40, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 324, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217385, 'OLE error 0x80041017', None, None)
2022-12-11 18:58:55 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:110)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 107, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 57, in get_current_window
  File "aw_watcher_window\lib.py", line 40, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 324, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217385, 'OLE error 0x80041017', None, None)
2022-12-11 19:05:01 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:110)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 107, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 57, in get_current_window
  File "aw_watcher_window\lib.py", line 40, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 324, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217385, 'OLE error 0x80041017', None, None)
2022-12-11 19:10:51 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:110)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 107, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 57, in get_current_window
  File "aw_watcher_window\lib.py", line 40, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 324, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217385, 'OLE error 0x80041017', None, None)
2022-12-11 19:12:39 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:110)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 107, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 57, in get_current_window
  File "aw_watcher_window\lib.py", line 40, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 324, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217385, 'OLE error 0x80041017', None, None)
```

**Comment by rannmann** [comment]
I'm getting the exact same error.  I just installed ActivityWatch yesterday, and the dashboard is entirely blank.  It takes at least a full minute to load to show "Time active: 0s"

**Comment by iloveitaly** [comment]
https://github.com/ActivityWatch/aw-watcher-window/pull/69 has fixed the issue for me. Will try to update the PR and get it merged!

**Comment by IamRezaMousavi** [comment]
It's fixed for me.
