### ISSUE TITLE
[Linux] 'BadRRModeError' object has no attribute 'sequence_number'

### ISSUE THREAD

**Issue by squigglezworth** [ActivityWatch/aw-watcher-window#89]
`aw-watcher-window` randomly encounters this error, which then causes it to hang with high CPU usage. This is probably related to https://github.com/python-xlib/python-xlib/issues/241
Please let me know what other information I should provide

```2023-04-04 21:20:12 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 106, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 59, in get_current_window
  File "aw_watcher_window/lib.py", line 17, in get_current_window_linux
  File "aw_watcher_window/xlib.py", line 67, in get_window_name
  File "Xlib/xobject/drawable.py", line 476, in get_full_property
  File "Xlib/xobject/drawable.py", line 455, in get_property
  File "Xlib/protocol/rq.py", line 1368, in __init__
  File "Xlib/protocol/rq.py", line 1380, in reply
  File "Xlib/protocol/display.py", line 612, in send_and_recv
  File "Xlib/protocol/display.py", line 719, in parse_response
  File "Xlib/protocol/display.py", line 745, in parse_error_response
AttributeError: 'BadRRModeError' object has no attribute 'sequence_number'```

**Comment by qz4** [comment]
I just experienced the same issue.
I do not know any way to reproduce the error.

Arch Linux x86_64 6.4.11-arch2.1
Xorg 1.21.1.8
KDE Plasma 5.27.7

[aw-watcher-window_2023-08-22T10-03-05.log](https://github.com/ActivityWatch/aw-watcher-window/files/12413197/aw-watcher-window_2023-08-22T10-03-05.log)

![image](https://github.com/ActivityWatch/aw-watcher-window/assets/12830098/0ad30bc4-d6ee-4956-ad04-bcd0682014af)
![flamegraph](https://github.com/ActivityWatch/aw-watcher-window/assets/12830098/fa534f1f-7ccc-4844-810c-556f61b701f1)

**Comment by ErikBjare** [comment]
I just experienced the same issue. Lost an hour of data. Frustrating.

Considering downgrading xlib to resolve the issue, but left a message on https://github.com/python-xlib/python-xlib/pull/242 hoping it will be considered for merge.

**Comment by ErikBjare** [comment]
Just bumped into this again. Frustrating!

Pinned python-xlib==0.31 in https://github.com/ActivityWatch/aw-watcher-window/commit/1a334d804262419e5276bc24202964bfb4ce4c00. Will soon be out in new beta v0.12.3b10.

**Comment by squigglezworth** [comment]
Thanks for your work, @ErikBjare!
