### ISSUE TITLE
[Windows] Exception thrown while trying to get active window

### ISSUE THREAD

**Issue by BelKed** [ActivityWatch/aw-watcher-window#90]
[Reported](https://discord.com/channels/755040852727955476/755334543891759194/1097209893779427389) by `@Creve` on Discord.

---

**Logs:**
```
2023-04-16 18:56:19 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 106, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 65, in get_current_window
  File "aw_watcher_window\lib.py", line 42, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "aw_watcher_window\windows.py", line 15, in get_app_path
pywintypes.error: (87, 'OpenProcess', 'Параметр задан неверно.')
```

---

- **OS:** Windows
- **ActivityWatch:** ActivityWatch `v0.12.3b1`

**Comment by hashblen** [comment]
Same. I'm also getting this Access denied error, jus tafter updating from a pretty old version, when playing a certain game that has administrator rights. Why did it work before I updated, I don't know. Hoping for a fix :)

**Comment by xpagedeveloper** [comment]
Still a problem in version 0.13.2

**Comment by stevensultana** [comment]
`pywintypes.error: (87, 'OpenProcess', 'The parameter is incorrect.')` happens when the hwnd is zero. (Or at least, that's the case I noticed). The UAC prompt is one such example when hwnd is zero. The logonUI.exe (when the user is entering username+password) is another case. Probably when there are secure tasks being done.

A possible fix is to skip/ignore hwnd==0 - resulting in an empty gap in the timeline. Downside is if there are some other cases where hwnd==0, but they need to be logged.

A second option is to catch hwnd==0, and check if UAC or logonUI.exe are running (then ignore or log them). If they are not running, throw an exception since it is an unknown case.

I have both solutions proposed. @ErikBjare, let me know if this is interesting and if you'd like me to open a PR for it.

**Comment by TimeToBuildBob** [comment]
Opened a fix in #118 — two changes:

1. **Early return for `hwnd == 0`**: When there's no foreground window (UAC prompt, lock screen, secure desktop), we now skip the poll cycle gracefully instead of hitting `OpenProcess` with PID 0.

2. **Wrapped WMI fallback**: If both `get_app_name()` and `get_app_name_wmi()` fail for elevated processes, we degrade to `"unknown"` instead of propagating exceptions (which caused the continuous error spam).

@stevensultana went with your first proposed solution (skip hwnd==0). The WMI fallback wrapping is a bonus to handle edge cases where WMI is also unavailable.
